config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  
  resources :customers, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include CustomersHelper
  def index
    @customers = Customer.search(params[:search])
  end

  def new
    @customer = Customer.new
  end

  def create
    email = params[:email]
    customer_params = extract_params_from_email(email)
    puts customer_params
    
    customer = Customer.new(customer_params)
    
    if customer.save
      redirect_to root_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def extract_params_from_email(text)
    return {
      name: text.string_between_markers('Name : ', '\r'),
      email: text.string_between_markers('Email : ', '\r'),
      phone: text.string_between_markers('Phone : ', '\r'),
      phone_ext: text.string_between_markers('EXT : ', '\r'),
      
      house_size: text.string_between_markers('Bedrooms : ', '\r'),
      distance: text.string_between_markers('Distance : ', '\r'),
      move_date: text.match(/^Move Date : (.*)/) ? text.match(/^Move Date : (.*)/)[1] : nil,
      
      from_areacode: text.string_between_markers('From Areacode : ', '\r'),
      from_city: text.string_between_markers('From City : ', '\r'),
      from_state: text.string_between_markers('From State : ', '\r'),
      from_zip: text.string_between_markers('From Zip : ', '\r'),
      
      to_areacode: text.string_between_markers('To Areacode : ', '\r'),
      to_city: text.string_between_markers('To City : ', '\r'),
      to_state: text.string_between_markers('To State : ', '\r'),
      to_zip: text.string_between_markers('To Zip : ', '\r')
    }
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/customers/_customer.html.erb
<tr>
  <td><%= customer.name %></td>
  <td><%= customer.email %></td>
  <td><%= customer.phone %><% if customer.phone_ext && customer.phone_ext != "" %> ext. <%= customer.phone_ext %><% end %></td>
  <td><%= customer.from_areacode %></td>
  <td><%= customer.from_zip %></td>
  <td><%= customer.from_state %></td>
  <td><%= customer.from_city %></td>
  <td><%= customer.to_areacode %></td>
  <td><%= customer.to_zip %></td>
  <td><%= customer.to_state %></td>
  <td><%= customer.to_city %></td>
  <td><%= customer.house_size %></td>
  <td><%= customer.distance %></td>
  <td><%= customer.move_date %></td>
</tr>

app/views/customers/create.html.erb
<h1>Leads#create</h1>
<p>Find me in app/views/leads/create.html.erb</p>

app/views/customers/index.html.erb
<div class="container">
  <caption>
    <%= form_tag customers_path, method: :get, class: 'form-inline pull-left' do %>
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
      <%= submit_tag "Search", name: nil, class: 'btn btn-primary' %>
    <% end %>
    <%= link_to '+ Add New', new_customer_path, class: 'btn btn-default pull-right' %>
  </caption>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th colspan="4" class="text-center">From</th>
        <th colspan="4" class="text-center">To</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Areacode</th>
        <th>Zip</th>
        <th>State</th>
        <th>City</th>
        <th>Areacode</th>
        <th>Zip</th>
        <th>State</th>
        <th>City</th>
        <th>Bedrooms</th>
        <th>Distance</th>
        <th>Move Date</th>
      </tr>
    </thead>
    <tbody>
      <% if @customers.count > 0 %>
        <%= render @customers %>
      <% else %>
        <tr>
          <td colspan="14">
            <p class="text-center">
              No Results
            </p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<div class="container">
  <%= form_for Customer.new do |f| %>
    <div class="form-group">
      <%= label_tag :email, 'Lead Text' %>
      <%= text_area_tag :email, nil, { class: 'form-control', rows: 5, placeholder: 'Copy and paste lead text' } %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', customers_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Oncue Test</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>